config/routes.rb
Rails.application.routes.draw do
  # root path for non-logged-in users
  unauthenticated do
    root 'mobile_banking#welcome', as: :root_for_non_logged_in
  end

  # Devise routes for user authentication
  devise_for :users

  # Routes for logged-in users
  authenticated :user do
    # Root path for logged-in users
    root 'categories#index', as: :authenticated_root

    # Other category routes for logged-in users
    resources :categories, only: [:index, :new, :create] do
      resources :transfers, only: [:index, :new, :create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, :all, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  has_many :category_transfers, dependent: :destroy
  has_many :transfers, through: :category_transfers
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/category_transfer.rb
class CategoryTransfer < ApplicationRecord
  belongs_to :category
  belongs_to :transfer
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  has_many :category_transfers, dependent: :destroy
  has_many :categories, through: :category_transfers
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0.1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :transfers, dependent: :destroy, foreign_key: :author_id
  has_many :categories, dependent: :destroy, foreign_key: :author_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @categories = current_user.categories.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(category_params)
    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon, :author_id)
  end
end

app/controllers/mobile_banking_controller.rb
class MobileBankingController < ApplicationController
  def welcome; end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  def index
    @category = Category.find(params[:category_id])
    @transfers = @category.transfers.where(author_id: current_user.id).order(created_at: :desc)
  end

  def new
    @categories = current_user.categories.all
    @transfer = Transfer.new
  end

  def create
    category = Category.find(params[:transfer][:category_id])
    transfer = current_user.transfers.new(transfer_params)
    CategoryTransfer.create(category:, transfer:)
    if transfer.save
      flash[:notice] = 'Transfer was successfully created.'
      redirect_to category_transfers_path(category)
    else
      render 'new'
    end
  end

  private

  def transfer_params
    params.require(:transfer).permit(:name, :amount, :author_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/mobile_banking_helper.rb
module MobileBankingHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/views/categories/index.html.erb
<%= render partial: 'shared/nav', locals: {
  header: 'Categories',
  left: '<span class="navbar-toggler-icon"></span>'.html_safe,
  right: button_to(
    "Logout",
    destroy_user_session_path,
    method: :delete,
    class: 'btn btn-link text-light fs-5 fw-bold',
    style: 'text-decoration: none;'
  )
} %>
<div class="container mt-3">
    <ul>
        <% @categories.each do |category|%>
            <li>
                 <%= render partial: 'shared/category_card', locals: {category: category} %>
            </li>
        <%end%>
    </ul>
    <%= content_tag :div, class: 'text-center cat-btn-cont' do%>
        <div class="cat-btn"><%= link_to 'New Category', new_category_path, class: 'btn text-light' %></div>
    <%end%>
</div>

app/views/categories/new.html.erb
<div class="container row justify-content-center align-items-center mt-5">
    <div class="col-md-6">
      <div class="form-container">
        <%= link_to categories_path do %>
            <i class="fa fa-arrow-left text-dark back-arrow"></i>
        <%end%>
        <h2 class="h2 text-center">Add New Category</h2>
          <%= form_with(model: @category, url: categories_path, method: :post) do |form| %>
            <div class="mb-3">
                <%= form.label :name, class: 'form-label' %>
                <%= form.text_field :name, class: 'form-control' %>
            </div>
            <div class="mb-3">
                <%= form.label :icon, class: 'form-label' %>
                <%= form.text_field :icon, class: 'form-control' %>
            </div>
            <div>
                <%= form.submit "Create Category", class: "btn btn-secondary" %>
            </div>
        <%end%>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mobile_banking/welcome.html.erb
<div class="container d-flex flex-column justify-content-between align-items-center height">
    <h1 class="h1 margin-top app-name">Mobile Banking</h1>
    <div class="d-flex flex-column w-100">
        <%= link_to "Log in", new_user_session_path, class: 'btn btn-primary p-3 mb-2' %>
        <%= link_to "Sign up", new_user_registration_path, class: 'btn p-3' %>
    </div>
</div>

app/views/shared/_category_card.html.erb
<%@total_amount = category.transfers.sum(:amount)%>
<div class="d-flex flex-row justify-content-between align-items-center card-body mb-3" style="height: 20vh">
    <div class="d-flex flex-row">
        <img src=<%= category.icon%> class="cat-img">
        <div class="d-flex flex-column justify-content-end">
            <h4 class="cat-name"><%= link_to category.name, category_transfers_path(category)%></h4>
            <span class="cat-date"><%= category.created_at.strftime('%d %B %Y')%></span>
        </div>
    </div>
    <div class="cat-total fw-bold">$<%= @total_amount%></div>
</div>

app/views/shared/_nav.html.erb
<nav class="container navbar navbar-expand-md navbar-light justify-content-between" style="background-color: #3778c2; height: 15vh">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
    <span><%= left%></span>
  </button>
  
  <a class="navbar-brand text-light fs-3 fw-bold" href="#"><%= header%></a>
  <div>
    <%= right%>
  </div>
</nav>
<p style="margin: 0"><%= notice %></p>
<p style="margin: 0"><%= alert %></p>

app/views/transfers/index.html.erb
<div class="container trans-header text-light mb-3">
    <%= link_to categories_path do %>
        <i class="fa fa-arrow-left text-light back-arrow"></i>
    <%end%>
    <h1 class="h3 trans-title">Transfers</h1>
</div>
<div class="container">
    <%= render partial: 'shared/category_card', locals: {category: @category}%>
    <ul>
        <%@transfers.each do |transfer| %>
            <li class="mb-3 p-2">
                <p class="trans-font"><%= transfer.name%></p>
                <div class="d-flex flex-row align-items-center trans-date">
                    <i class="fa fa-regular fa-calendar me-3"></i>
                    <div><%= transfer.created_at.strftime('%d %B %Y at %l:%M %P')%></div>
                </div>
            </li>
        <%end%>
    </ul>
    <%= content_tag :div, class: 'text-center cat-btn-cont' do%>
        <div class="cat-btn"><%= link_to 'New Transfer', new_category_transfer_path(@category), class: 'btn text-light' %></div>
    <%end%>
</div>

app/views/transfers/new.html.erb
<div class="container row justify-content-center align-items-center mt-5">
    <div class="col-md-6">
      <div class="form-container">
        <%= link_to category_transfers_path do %>
            <i class="fa fa-arrow-left text-dark back-arrow"></i>
        <%end%>
        <h2 class="h2 text-center">Add New Transfer</h2>
          <%= form_with(model: @transfer, url: category_transfers_path, method: :post) do |form| %>
            <div class="mb-3">
                <%= form.label :name, class: 'form-label' %>
                <%= form.text_field :name, class: 'form-control' %>
            </div>
            <div class="mb-3">
                <%= form.label :amount, class: 'form-label' %>
                <%= form.text_field :amount, class: 'form-control' %>
            </div>
            <div class="mb-3">
                <%= form.label :category, class: 'form-label' %>
                <%= form.select :category_id, @categories.map { |category| [category.name, category.id] }, {}, { class:'form-select'} %>
            </div>
            <div class="text-center">
                <%= form.submit "Create Transfer", class: "btn btn-secondary" %>
            </div>
        <%end%>
      </div>
    </div>
  </div>